version: "3"
services:
  masternotebook:
    build:
      context: .
      dockerfile: Dockerfile-notebook
    command: start-notebook.sh --NotebookApp.token=''
    hostname: master
    environment:
      - SPARK_CONF_DIR=/conf
      - SPARK_PUBLIC_DNS=localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
      - 8888:8888
    volumes:
      - ./conf/master:/conf
      - ./notebooks/work:/home/jovyan/work
      - ./notebooks/startup:/home/jovyan/.ipython/profile_default/startup
      - ./templates/notebooks:/home/jovyan/templates/notebooks
      - ./tests:/home/jovyan/tests
