FROM jupyter/pyspark-notebook:83ed2c63671f

USER $NB_USER
RUN mkdir -p /home/jovyan/.ipython/profile_default

ADD ./requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Download necessary data for nltk
RUN python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
